version: '3'
services:

  springappserver:
    build:
      context: .
    ports:
    - "8080:8080"
    networks:
    - mt-network
    volumes:
    - .:/vol/development
    depends_on:
    - mysqldbserver

  mysqldbserver:
    image: mysql:5.7
    restart: always
    container_name: feedback_db
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
    networks:
    - mt-network
    volumes:
    - my-db:/var/lib/mysql

networks:
  mt-network:
    driver: bridge

volumes:
  my-db: